version: '2'

services:
  jenkins:
    restart: "no"
    image: jenkins/jenkins:2.147
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /srv/docker/jenkins/docker.sock:/var/run/docker.sock
      - /srv/docker/jenkins:/var/jenkins_home