  # Docker-in-Docker Gitlab runners setup taken from:
  # https://medium.com/@tonywooster/docker-in-docker-in-gitlab-runners-220caeb708ca
  dind:
    restart: always
    privileged: true
    volumes:
    - /srv/docker/runner/var/lib/docker:/var/lib/docker
    image: docker:17.09.0-ce-dind
    command: 
    - --storage-driver=overlay2

  runner:
    restart: always
    image: gitlab/gitlab-runner:alpine
    volumes:
    - /srv/docker/runner:/etc/gitlab-runner:Z
    environment:
    - DOCKER_HOST=tcp://dind:2375

  register-runner:
    restart: 'no'
    image: gitlab/gitlab-runner:alpine
    volumes:
    - /srv/docker/runner:/etc/gitlab-runner:Z
    command:
    - register
    - --non-interactive
    - --locked=false
    - --name=Docker Runner
    - --executor=docker
    - --docker-image=docker:17.09.0-ce-dind
    - --docker-volumes=/var/run/docker.sock:/var/run/docker.sock
    environment:
    - CI_SERVER_URL=http://nola.ipdisk.co.kr:10080/
    - REGISTRATION_TOKEN=zV-KmYjy8Fs5Rp27zyWo