GitlabCIMultiRunner:
  image: sameersbn/gitlab-ci-multi-runner:1.1.4-7
  volumes:
    - /srv/docker/gitlab-runner:/home/gitlab_ci_multi_runner/data
  environment:
    - CI_SERVER_URL=http://nola.ipdisk.co.kr:10080/
    - RUNNER_TOKEN=cQ2gVDYivp8G2p_5n2D9
    - RUNNER_DESCRIPTION=myrunner
    - RUNNER_EXECUTOR=shell
  restart: always